version: 0.2
phases:
  build:
    commands:
        - export BUCKET=myserverlesscodepipelinebucket
        - sam package --template-file template.yaml --output-template-file deploy.yaml --s3-bucket $BUCKET
        - sam deploy --template-file deploy.yaml --stack-name mysamstack7 --capabilities CAPABILITY_IAM --region us-east-1 --role-arn arn:aws:iam::581209585450:role/myapp-cloudformation-role
artifacts:
  type: zip
  files:
    - template.yaml
    - deploy.yaml
