version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
        - npm install
        - export BUCKET=myserverlesscodepipelinebucket
        - sam build --template template.yaml
        - sam package --template-file .aws-sam/build/template.yaml --output-template-file deploy.yaml --s3-bucket $BUCKET
        - sam deploy --template-file deploy.yaml --stack-name mysamstack61 --capabilities CAPABILITY_IAM --region us-east-1
artifacts:
  type: zip
  files:
    - template.yaml
    - deploy.yaml
