AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:581209585450:userpool/us-east-1_uCuKaMzo6
            Identity:
              Header: Authorization

  ApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: index.lambda_handler
      Role: arn:aws:iam::581209585450:role/LambdaAuroraRrole
      Runtime: python3.7
      VpcConfig:
        SubnetIds:
          - subnet-0b90441611c4b9a3e
          - subnet-0415d65a0dade3f67 
        SecurityGroupIds:
          - sg-0af396943d01e2851
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Path: /tempp
            Method: get
            Auth:
              Authorizer: MyCognitoAuthorizer
            RestApiId:
              Ref: ApiGatewayApi
